#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Enig config
autoload -Uz promptinit
promptinit
prompt enigmoid

set -o vi
export EDITOR=vim
export TERM="xterm-256color"

[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

function jj() {
	j $* | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"
}

alias viminstall='vim +BundleInstall +qall'

# Mongo stuff
export MONGOURI_TWOTER='mongodb://enigmoid:wasspord@ds045531.mongolab.com:45531/twoter'

export FACEBOOK_clientID='839520142782453'
export FACEBOOK_clientSecret='7be992bb6e4ffdd7510845c229b3670f'
export FACEBOOK_callbackURL='http://localhost:3000/auth/facebook/callback'

# edit and autosave zshrc
alias zrc='vim ~/.zshrc;. ~/.zshrc'
alias b='brew'
alias doctorb='brew doctor'
alias o='open'
alias ql='qlmanage -p'
alias py3='python3'
alias py='python2'
alias ipn='ipython notebook --matplotlib inline'
alias ip='ipython --matplotlib'
alias q='qlmanage -p '
alias calc='dc'
alias ij='cd ~/Notebook; ipython notebook --profile julia'
alias re='eval $(thefuck $(fc -ln -1))'

alias ssheducanontest='ssh -R 52698:localhost:52698 educanontest'
alias rrshell='ssh rshell'
alias mat='. /Applications/MATLAB_R2014b.app/bin/matlab -nodesktop -nosplash'

alias fswatch='stylus -w stylus --out static/stylesheets'

alias eswatch='stylus -w stylus --out stylesheets'
alias jerve='bundle exec jekyll serve -w'
alias catch='coffee -wco js coffee'

alias evan='cd ~/Git/enigmoid.github.io; jerve'

alias jatch='jade -w jade --out .'
alias resumevan='cd ~/Git/resume; grunt jade-pygments; grunt watch'

alias pandora='pianokeys && pianobar'
alias internet='ping -a 8.8.8.8'

# Basic aliases
alias c='pbcopy'
alias p='pbpaste'
alias l='ls -Gh'
alias ll='ls -Glh'
alias la='ls -Glah'
alias cl='c && l'
alias cll='c && ll'
alias cla='c && la'
alias lt='ls -Gctlh'
alias less='less -R'
alias more='less'
alias pwc='pwd|pbcopy'
alias cdc='cd "`pbpaste`"'
alias mo='open -a Mou'
alias so='open -a Sublime\ Text'
alias e='echo'
alias deject='diskutil eject Desktop'
alias ndm='nodemon --ignore public'

# wiki aliases
alias ndmw='ndm & ./watch.sh'

# Git plugin overrides
alias gi='git init'
alias ga='git add'
alias gc='git commit'
alias go='git show'
alias gs='git status'
alias gsta='git status'
alias gst='git stash'
alias gd='git diff'
alias gD='git diff --word-diff'
alias gdc='git diff --cached'
alias gDc='git diff --word-diff --cached'
alias gl='git l'
alias go='git clone'
alias ge='git checkout'
alias gu='git pull'
alias grc='git rebase --continue'

# MADVLSI
alias magic='magic -T SCN3ME_SUBM.30'
alias vlsicd='cd /media/psf/Home/Semester/MADVLSI/Machine\ Problem\ 4/'
alias mac='cd /media/psf/Home'
alias macdir='/media/psf/Home'
alias ltspice='wine /Users/Enigmoid/.wine/drive_c/Program\ Files/LTC/LTspiceIV/scad3.exe'

# Bayesian
alias bipn='cd ~/Semester/Bayesian/Notebook; ipn'

# Hacking aliases
alias luna='ssh -Y enigmoid@evan-luna'
alias buntu='ssh -Y enigmoid@10.211.55.10'
alias suntu='prlctl start Ubuntu'
alias stuntu='prlctl stop Ubuntu'
alias spuntu='prlctl suspend Ubuntu'
alias buntu-connect='prlctl set Ubuntu --device-connect '
alias buntu-device-list='prlsrvctl info'
alias edi='ssh root@esatellite.local'

# Fun
alias isjsup='echo GET / HTTP/1.1\\n\\n | nc olinjs.github.io 80 | head -n 1 | sed "s:\(.*404.*\):no:" | sed "s:\(.*200.*\):yes:" | say'

alias easter='ncal -e'

alias sasquatch='sass --watch www/static/scss:www/static/css'
alias edsync='rsync -avz --delete --exclude=tmp/ ~/Code/educanonllx/* educanontest:~/educanon/'
alias cdprompt='cd ~/.zprezto/modules/prompt/functions'

# Ubuntu
alias sapt='sudo apt-get'
alias sapty='sudo apt-get -y'

# Functions

# was going to make functions to cd after mv or cp, but then discovered
# cd !$

function pulseon() {
	cd /Applications/Junos\ Pulse.app/Contents/Plugins/JamUI/
	sudo mv PulseTray.app.off PulseTray.app
	cd --
}

function pulseoff() {
	cd /Applications/Junos\ Pulse.app/Contents/Plugins/JamUI/
	sudo mv PulseTray.app PulseTray.app.off
	killall PulseTray
	cd --
}  

# Show all 256 colors with color number
function spectrum_ls() {
  for code in {000..255}; do
    print -P -- "$code: %F{$code}The words were colored.%f"
  done
}

# Show all 256 colors where the background is set to specific color
function spectrum_bls() {
  for code in {000..255}; do
    print -P -- "$BG[$code]$code: The colors were worded. %{$reset_color%}"
  done
}

# Mount Olin Samba Shares
function olinmount() {
	for share in $*;
		do
		mkdir /Volumes/$share;
		mount -t smbfs //edorsky@fsvs01/$share /Volumes/$share;
	done;
}

# I wouldn't trust this
function cpstat () {
  tar cf - "$1" | pv | (cd "$2";tar xf -)
}

export NVM_DIR=~/.nvm
source $NVM_DIR/nvm.sh
[[ -r $NVM_DIR/bash_completion ]] && . $NVM_DIR/bash_completion
